[build]
  # Build command
  command = "npm run build"
  
  # Publish directory (Next.js static export output)
  publish = "out"
  
  # Base directory (if needed)
  # base = "/"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # Build environment variables
  NODE_ENV = "production"

# Redirects for Next.js routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Environment-specific configurations
[context.production.environment]
  # Production environment variables
  NODE_ENV = "production"

[context.deploy-preview.environment]
  # Preview environment variables
  NODE_ENV = "preview"

[context.branch-deploy.environment]
  # Branch deploy environment variables
  NODE_ENV = "development"
